from .representation.genome import (
    Genome,
    Segment,
    CrossoverFn,
    MutationFn,
)
from .representation.lineage import Lineage
from .representation.individual import Individual
from .representation.population import Population
from .variation.selection import (
    SelectionStrategy,
    select,
    TournamentSelection,
    RouletteWheelSelection,
    StochasticUniversalSamplingSelection,
    LinearRankSelection,
    ExponentialRankSelection,
    TruncationSelection,
    ElitistSelection,
    RandomSelection,
    BoltzmannSelection,
)
from .variation.recombination import (
    RecombinationStrategy,
    recombine,
    n_point_crossover,
    ElementwiseCrossover,
    OnePointCrossover,
    TwoPointCrossover,
    NPointCrossover,
    RandomNPointCrossover,
    UniformCrossover,
    ShuffleCrossover,
    OrderCrossover,
    PartiallyMatchedCrossover,
    CycleCrossover,
    ArithmeticCrossover,
    BlendCrossover,
    SimulatedBinaryCrossover,
)
from .variation.mutation import (
    MutationStrategy,
    mutate,
    UniformMutation,
    InversionMutation,
    SwapMutation,
    ScrambleMutation,
    InsertionMutation,
    TranspositionMutation,
    DuplicationMutation,
    DeletionMutation,
    GaussianMutation,
    UniformRealMutation,
    PolynomialMutation,
    CauchyMutation,
    BitFlipMutation,
    BoundaryMutation,
    gaussian_noise_mutator,
    bit_flip_mutator,
    attribute_mutator,
)
from .replacement import (
    ReplacementStrategy,
    replace,
    GenerationalReplacement,
    PlusReplacement,
    CommaReplacement,
    SteadyStateReplacement,
)
from .pipeline import (
    EvolutionPipeline,
    step,
)
from .builders import (
    build_selection_strategy,
    build_crossover_strategy,
    build_mutation_strategy,
    build_replacement_strategy,
    build_pipeline,
)
from .registry import (
    register_selection,
    get_selection_strategy,
    list_selection_strategies,
    register_crossover,
    get_crossover_strategy,
    list_crossover_strategies,
    register_mutation,
    get_mutation_strategy,
    list_mutation_strategies,
    register_replacement,
    get_replacement_strategy,
    list_replacement_strategies,
)

__all__ = [
    # Representation
    "Genome",
    "Segment",
    "CrossoverFn",
    "MutationFn",
    "Lineage",
    "Individual",
    "Population",
    # Variation - Parent Selection
    "SelectionStrategy",
    "select",
    "TournamentSelection",
    "RouletteWheelSelection",
    "StochasticUniversalSamplingSelection",
    "LinearRankSelection",
    "ExponentialRankSelection",
    "TruncationSelection",
    "ElitistSelection",
    "RandomSelection",
    "BoltzmannSelection",
    # Variation - Recombination
    "RecombinationStrategy",
    "recombine",
    "n_point_crossover",
    "ElementwiseCrossover",
    "OnePointCrossover",
    "TwoPointCrossover",
    "NPointCrossover",
    "RandomNPointCrossover",
    "UniformCrossover",
    "ShuffleCrossover",
    "OrderCrossover",
    "PartiallyMatchedCrossover",
    "CycleCrossover",
    "ArithmeticCrossover",
    "BlendCrossover",
    "SimulatedBinaryCrossover",
    # Variation - Mutation
    "MutationStrategy",
    "mutate",
    "UniformMutation",
    "InversionMutation",
    "SwapMutation",
    "ScrambleMutation",
    "InsertionMutation",
    "TranspositionMutation",
    "DuplicationMutation",
    "DeletionMutation",
    "GaussianMutation",
    "UniformRealMutation",
    "PolynomialMutation",
    "CauchyMutation",
    "BitFlipMutation",
    "BoundaryMutation",
    "gaussian_noise_mutator",
    "bit_flip_mutator",
    "attribute_mutator",
    # Replacement (Survivor Selection)
    "ReplacementStrategy",
    "replace",
    "GenerationalReplacement",
    "PlusReplacement",
    "CommaReplacement",
    "SteadyStateReplacement",
    # Pipeline
    "EvolutionPipeline",
    "step",
    # Declarative Builders
    "build_selection_strategy",
    "build_crossover_strategy",
    "build_mutation_strategy",
    "build_replacement_strategy",
    "build_pipeline",
    # Registry
    "register_selection",
    "get_selection_strategy",
    "list_selection_strategies",
    "register_crossover",
    "get_crossover_strategy",
    "list_crossover_strategies",
    "register_mutation",
    "get_mutation_strategy",
    "list_mutation_strategies",
    "register_replacement",
    "get_replacement_strategy",
    "list_replacement_strategies",
]

